name: Build README

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate README (Cloud Posse style)
        run: make readme

      - name: Inject Terraform Docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"